# Site settings
title: Maciej's Playground
description: "Maciej Czuchnowski's personal website"
url: "http://mczuchnowski.github.io"
author:
  name: "Maciej Czuchnowski"
  url: "http://mczuchnowski.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site

# Default values
defaults:
  -
    scope:
      path: ""

# Options
custom_header: false
custom_nav_footer: false
reverse: false

plugins: []
